### ISSUE TITLE
Fix readAll() method in FileParser class

### ISSUE THREAD

**Issue by sushchyk** [Sipleman/euro-diffusion#2]
https://github.com/Sipleman/euro-diffusion/blob/68cf750eef008e6195109fc8c1bae41beb8f6d7c/src/com/company/utils/FileParser.java#L21-L41
Додати обробку всіх можливих помилок(пустий файл, немає  нуля в кінці і т.д.), а не тільки коли лінія в файлі не відповідає регулярці.

**Comment by Sipleman** [comment]
closed by PR #6 .
