### ISSUE TITLE
Make Event an interface

### ISSUE THREAD

**Issue by sushchyk** [Sipleman/euro-diffusion#5]
https://github.com/Sipleman/euro-diffusion/blob/68cf750eef008e6195109fc8c1bae41beb8f6d7c/src/com/company/model/events/Event.java#L3
Зробити клас Event інтерфесом.

**Comment by Sipleman** [comment]
@sushchyk 
Лучше сделать его абстрактным и хранить общие для двух ивентов поля. Поэтому следующим комитом всё отрефакторю.
